### ISSUE TITLE
Nazwy własne angielskie przedmiotów i potworów.

### ISSUE THREAD

**Issue by Tomonike** [jdarowski/PolishTranslation#3]
Mam pytanie odnośnie nazw przedmiotów, potworów i lokalizacji, czy one też będą przetłumaczone ?
Mi chodzi o to że gdy przetłumaczy się na język polski wszystkie te rzeczy, potem jest problem z dogadaniem się po angielsku ponieważ nazwa jest inna. Szczególnie to dotyczy lokacji i przedmiotów.
Przykład np gra Aion. Bez polskiego serwera tłumaczenie polskie do niczego się nie nadawało, nie wiadomo było o co chodzi. Dlatego też sugerowałbym na zostawienie nazewnictwa oryginalnego by była spójność. Wiem że to trochę nie do końca po polsku ale lepiej by się gracze mogli dogadać. Jeżeli byśmy dostali oddzielny serwer wtedy to nie ma problemu. 

Pozdrawiam. :)

**Comment by jdarowski** [comment]
Nazwy własne powinny być tłumaczone w **umiarkowany** sposób. Oznacza to mniej więcej tyle, że _Chronomancer_ będzie po polsku _Chronomantą_, a nie _Zaklinaczem Czasu_.
Przykład z referencji:
- Kaliss Province = Prowincja Kaliss

Natomiast nazwy całkowicie własne powinny pozostać niezmienione. W ten sposób Klaipeda pozostaje Klaipedą, a Veinika Veiniką.

Oczywiście **zapraszam do dyskusji!** Moje zdanie nie jest ostateczne ani jedyne, a do nieomylności mi daleko :)

**Comment by Tomonike** [comment]
Takie tłumaczenie to ja rozumiem. Właśnie o to mi chodziło.
